AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - '*.spec'
    - 'Rakefile'

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 160

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
